# Generated by Django 4.0.10 on 2024-04-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0003_twit_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='twit',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
