# Generated by Django 4.0.10 on 2024-04-07 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twits', '0006_alter_twit_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='twit',
            options={'ordering': ['-created']},
        ),
    ]
